version: '3.7'

services:
  polynote:
    image: lolhens/polynote
    environment:
      POLYNOTE_CONFIG: |
        listen:
          host: 0.0.0.0
          port: 8192
    ports:
      - "8192:8192"
    volumes:
      - notebooks:/opt/polynote/notebooks

volumes:
  notebooks:

